---
title: "Group 42 CA pollution burden"
author: "Sophia Leiker, Evie Vermeer"
date: "11/11/2021"
output: html_document
---

```{r setup, include=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

#Attaching packages
library(tidyverse)
library(janitor)
library(here)
library(hexbin)
```

```{r}
ces <- read_csv(here("data", "ces3demographics.csv")) %>% 
  janitor::clean_names()
```

```{r}
ggplot(data=ces, aes(x=white_percent, y=ces_3_0_score))+
  geom_hex() +
  labs(x = "Percent White Population", y = "CalEnviroScreen 3.0 Score", title = "Relationship Between Percent White Population and CES 3.0 Score", subtitle = "Data from CEJA Green Zones Manager Tiffany Eng")+
  scale_fill_gradient(low="paleturquoise", high="royalblue4")+
  theme_minimal()

```

**Figure 1**: A comparison between percent white population and the CalEnviroScreen 3.0 Score. Darker blue values indicate a higher count of observations, lighter blue values indicate a lower count of observations. 